### PR TITLE
Formatting for output explorer

### PR DESCRIPTION
**Pull request by benbc**
There are [before](https://github.com/opensafely/output-explorer-test-repo/blob/master/test-outputs/vaccine-coverage-original.html) and [after](https://github.com/opensafely/output-explorer-test-repo/blob/master/test-outputs/vaccine-coverage-new.html) versions of the output available.

### CODE REVIEW

**Review by inglesp — COMMENTED** [review]
Changes look sensible, but I don't think we should merge until we know that we will render the reports via the new output viewer, and not via opensafely.org.

**Comment by benbc** [comment]
> Changes look sensible, but I don't think we should merge until we know that we will render the reports via the new output viewer, and not via opensafely.org.

@inglesp What needs to happen to clarify that?

**Comment by inglesp** [comment]
> What needs to happen to clarify that?

If we're planning to continue to show reports at the bottom of https://www.opensafely.org/research/2021/covid-vaccine-coverage/, then we can't merge this PR, because it'll change how the reports are rendered.  In particular, we've lost all the styling, the images are outsized, and there are pilcrows everywhere!

The time to merge this will be when the output viewer is live.  Then we can replace the reports at the bottom of https://www.opensafely.org/research/2021/covid-vaccine-coverage/ with a link to the output viewer, and share the URL of the output viewer as the canonical place to view the report.

Does that make sense?

**Review by inglesp — APPROVED** [review]

**Comment by benbc** [comment]
Closed in favour of https://github.com/opensafely/covid-vaccine-preliminary-uptake-study/pull/115.

**Pull request closed without merging**
